application: p2-gae
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: .*
  script: blogger.app

libraries:
- name: webapp2
  version: "2.5.2"
